baseURL = 'https://dirgames.com/editorial/'
title = 'C:\>DIR GAMES'

theme = 'soho'

enableEmoji = true
enableGitInfo = true

languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[params]
	author = 'Daniel Saner'
	license = 'CC BY-NC-SA 4.0'
	licenseURL = 'https://creativecommons.org/licenses/by-nc-sa/4.0/'

	themeColor = '#202020'
	customCss = ['css/dirgames.css']
	
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
		disable = true
	[privacy.youtube]
		disable = true

[languages]
	[languages.en]
		languageName = 'English'
		languageFlag = '🇬🇧'
		weight = 1
		[languages.en.params]
			copyright = 'for textual content: Daniel Saner'
			stringReadTimeMinutes = 'minute read'
		[languages.en.menu]
			[[languages.en.menu.main]]
				name = 'Home'
				url = '/en'
				weight = 1
			[[languages.en.menu.main]]
				name = 'About'
				url = '/en/about'
				weight = 2
			[[languages.en.menu.main]]
				name = 'Latest'
				url = '/en/articles'
				weight = 3
			[[languages.en.menu.main]]
				name = 'Projects'
				url = '/en/articles/projects'
				weight = 4
	[languages.de]
		languageName = 'Deutsch'
		languageFlag = '🇩🇪'
		weight = 10
		[languages.de.params]
			copyright = 'für Textinhalte: Daniel Saner'
			stringReadTimeMinutes = 'Minuten Lesezeit'
		[languages.de.menu]
			[[languages.de.menu.main]]
				name = 'Start'
				url = '/de'
				weight = 1
			[[languages.de.menu.main]]
				name = 'Infos'
				url = '/de/about'
				weight = 2
			[[languages.de.menu.main]]
				name = 'Neues'
				url = '/de/articles'
				weight = 3
			[[languages.de.menu.main]]
				name = 'Projekte'
				url = '/de/articles/projects'
				weight = 4

[taxonomies]
	category = 'categories'
	series = 'series'
	tag = 'tags'
